### ISSUE TITLE
Create function to get location IDs

### ISSUE THREAD

**Issue by AugustT** [FrancescaMancini/FlickrAPI_EABhackathon#2]
This can be done using the flickr.places.find API

**Comment by FrancescaMancini** [comment]
That's a good idea!
flickr.places.find will return info about all places with the same name so we need to make sure the function will return all info so people can choose the one that is relevant for them.

**Comment by AugustT** [comment]
Yeah I think you are right. Louis is working on this now

**Comment by FrancescaMancini** [comment]
oops sorry, just saw this. I just pushed a script that starts doing that. I will leave it to Loius now.

**Comment by AugustT** [comment]
@FrancescaMancini Are you going to try and work on some scripts remotely? If so let us know so we dont duplicate effort.

**Comment by FrancescaMancini** [comment]
@AugustT yes, I was trying to. I will have to go through security and hopefully board my flight soon, so I won't be able to do much in the next couple of hours. But if there is any small task that you would like to assign me I can do some work on the plane and on the train.

**Comment by AugustT** [comment]
@louissutter has done this now
